import type { CollectionConfig } from 'payload'
import { isAdmin, isAuthed, isEditorOrAdmin } from '../access/byRole'
import { checkIfUnmodifiedSince } from '../hooks/checkIfUnmodifiedSince'
import { segmentChinese } from '../hooks/segmentChinese'
import { setLastEditedBy } from '../hooks/setLastEditedBy'
import { updateTranscriptionSearchVector } from '../hooks/updateSearchVector'

export const Transcriptions: CollectionConfig = {
  slug: 'transcriptions',
  admin: {
    useAsTitle: 'document',
    defaultColumns: ['document', 'transcriber', 'updatedAt'],
    listSearchableFields: ['text'],
  },
  access: {
    read: isAuthed,
    create: isEditorOrAdmin,
    update: isEditorOrAdmin,
    delete: isAdmin,
  },
  versions: {
    maxPerDoc: 20,
  },
  hooks: {
    beforeChange: [
      checkIfUnmodifiedSince,
      setLastEditedBy,
      ({ data }) => {
        // Re-segment on every save so textSegmented stays in sync with text.
        // Keeps Postgres tsvector indexing consistent.
        data.textSegmented = segmentChinese(data.text)
        return data
      },
    ],
    afterChange: [updateTranscriptionSearchVector],
  },
  fields: [
    {
      name: 'document',
      type: 'relationship',
      relationTo: 'documents',
      required: true,
      hasMany: false,
      admin: {
        description: 'Each Document has at most one Transcription.',
      },
    },
    {
      name: 'text',
      type: 'textarea',
      label: '中文录入',
      // Payload defaults textarea maxLength to 40000. Raise it well past any
      // realistic single transcription so long record books save cleanly.
      maxLength: 1_000_000,
    },
    {
      name: 'textSegmented',
      type: 'textarea',
      // segmentChinese inserts a space between every token, so this is roughly
      // 2x the length of `text`. Keep its cap proportionally higher than
      // `text` so it never trips before the (visible) source field does.
      maxLength: 2_500_000,
      admin: {
        hidden: true,
        readOnly: true,
        description: 'Auto-generated by nodejieba for search.',
      },
    },
    {
      name: 'transcriber',
      type: 'relationship',
      relationTo: 'users',
      hasMany: false,
    },
    {
      name: 'lastEditedBy',
      type: 'relationship',
      relationTo: 'users',
      hasMany: false,
      admin: {
        readOnly: true,
        description: 'Auto-set on every save.',
      },
    },
  ],
}
