import type { CollectionConfig } from 'payload'
import { segmentChinese } from '../hooks/segmentChinese'

export const Transcriptions: CollectionConfig = {
  slug: 'transcriptions',
  admin: {
    useAsTitle: 'document',
    defaultColumns: ['document', 'transcriber', 'updatedAt'],
  },
  versions: {
    maxPerDoc: 50,
  },
  hooks: {
    beforeChange: [
      ({ data }) => {
        // Re-segment on every save so textSegmented stays in sync with text.
        // Keeps Postgres tsvector indexing consistent.
        data.textSegmented = segmentChinese(data.text)
        return data
      },
    ],
  },
  fields: [
    {
      name: 'document',
      type: 'relationship',
      relationTo: 'documents',
      required: true,
      hasMany: false,
      admin: {
        description: 'Each Document has at most one Transcription.',
      },
    },
    {
      name: 'text',
      type: 'textarea',
      label: '中文 transcription',
    },
    {
      name: 'textSegmented',
      type: 'textarea',
      admin: {
        hidden: true,
        readOnly: true,
        description: 'Auto-generated by nodejieba for search.',
      },
    },
    {
      name: 'transcriber',
      type: 'relationship',
      relationTo: 'users',
      hasMany: false,
    },
  ],
}
